### ISSUE TITLE
How to use these methods?

### ISSUE THREAD

**Issue by wowfee** [Arg0s1080/statux#1]
hello,after installed the statux by pip,how could i use it? could you please give me some advices?

**Comment by Arg0s1080** [comment]
Hi, 

Use is usual with any python module. You can copy any example from the[ "examples" folder](https://github.com/Arg0s1080/statux/tree/master/examples) and test all methods described in [README](https://github.com/Arg0s1080/statux/blob/master/README.rst)

For example:

```sudo -H pip install statux```

Using python interpreter:

```yourname@yourdomain:~$ python3```

```python
>>> from statux.battery import wear_level, voltage
>>> print(str(wear_level()) + "% wear")
14.58% wear

>>> from statux.cpu import physical_cpus
>>> physical_cpus()
6
```
If you need more help I need you to be more specific please. Which module do you need to use?

Regards

**Comment by GanesanGuru** [comment]
Hi fellas, Whether it works in Raspberry Pi? I've got the following error!!

**pi@raspberrypi:~/Desktop $ python3 battery.py 
Traceback (most recent call last):
  File "battery.py", line 5, in <module>
    print(str(wear_level()) + "% wear")
  File "/home/pi/.local/lib/python3.7/site-packages/statux/battery.py", line 54, in wrapper
    raise ValueNotFoundError(get_name(), _PTH, err_no=error, msg=msg)
statux._errors.ValueNotFoundError: [Errno 42] No message of desired type: join() argument must be str or bytes, not 'NoneType': '/sys/class/power_supply/'**
